name: Push latest-images to docker
on:
  push:
    branches:
      - master

jobs:
  push-latest:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        push: ['push-latest']
    name: ${{ matrix.push }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push dope latest image
        run: |
          make ${{ matrix.push }}
      - name: Build and push d-action latest image
        run: |
          cd tools/d-action
          make ${{ matrix.push }}